SELECT first_name,hire_date,SYSDATE AS current_date FROM hr.employees;
SELECT first_name, hire_date,ADD_MONTHS(hire_date, 6) AS after_6_months FROM hr.employees;
SELECT first_name,hire_date,ADD_MONTHS(hire_date, 12) AS one_year_completion FROM hr.employees;
SELECT first_name, hire_date,ADD_MONTHS(hire_date, 24) AS two_year_completion FROM hr.employees;
SELECT first_name,hire_date,ADD_MONTHS(hire_date, -6) AS six_months_before FROM hr.employees;
SELECT first_name,hire_date,MONTHS_BETWEEN(SYSDATE, hire_date) AS months_worked FROM hr.employees;
SELECT first_name,hire_date,MONTHS_BETWEEN(SYSDATE, hire_date) / 12 AS years_worked FROM hr.employees;
SELECT first_name,hire_date,LAST_DAY(hire_date) AS last_day_of_month FROM hr.employees;
SELECT first_name,hire_date,NEXT_DAY(hire_date, 'MONDAY') AS next_monday FROM hr.employees;
SELECT first_name,hire_date,NEXT_DAY(hire_date, 'FRIDAY') AS next_friday FROM hr.employees;
SELECT first_name,hire_date,TRUNC(SYSDATE) AS today FROM hr.employees;
SELECT first_name,hire_date,TRUNC(hire_date, 'MONTH') AS first_day_of_month FROM hr.employees;
SELECT first_name,hire_date,TRUNC(hire_date, 'YEAR') AS first_day_of_year FROM hr.employees;
SELECT first_name,hire_date,TO_CHAR(hire_date, 'DD-MM-YYYY') AS formatted_hire_date FROM hr.employees;
SELECT first_name,hire_date,TO_CHAR(hire_date, 'MONTH') AS joining_month FROM hr.employees;
SELECT first_name,hire_date,TO_CHAR(hire_date, 'DAY') AS joining_day FROM hr.employees;
SELECT first_name,hire_date,hire_date + 30 AS after_30_days FROM hr.employees;
SELECT first_name,hire_date,hire_date - 30 AS before_30_days FROM hr.employees;
SELECT first_name,hire_date,TRUNC(SYSDATE) - TRUNC(hire_date) AS days_workedFROM hr.employees;
SELECT first_name,hire_date FROM hr.employees WHERE hire_date > TO_DATE('01-01-2005', 'DD-MM-YYYY');